"""empty message

Revision ID: 016ff87010b4
Revises: 1fd285330a4d
Create Date: 2020-10-19 17:13:09.443849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016ff87010b4'
down_revision = '1fd285330a4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cube_card', sa.Column('is_original', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cube_card', 'is_original')
    # ### end Alembic commands ###
