"""empty message

Revision ID: 06fe4ec0936e
Revises: fb248d1a0d01
Create Date: 2020-12-26 09:07:23.419392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06fe4ec0936e'
down_revision = 'fb248d1a0d01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('personas_tsv', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('portrait_link', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'portrait_link')
    op.drop_column('user', 'personas_tsv')
    # ### end Alembic commands ###
