"""Add levelups

Revision ID: 0d3ddd407bc1
Revises: 797050175eda
Create Date: 2021-01-16 16:54:17.335527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d3ddd407bc1'
down_revision = '797050175eda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('levelup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('reward', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('levelup_claim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('levelup_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('story', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['levelup_id'], ['levelup.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('levelup_claim')
    op.drop_table('levelup')
    # ### end Alembic commands ###
