"""empty message

Revision ID: 12cbef9e0868
Revises: 045addf59332
Create Date: 2020-10-15 17:36:54.027818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12cbef9e0868'
down_revision = '045addf59332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pack', sa.Column('did_scar', sa.Boolean(), nullable=True))
    op.add_column('scar', sa.Column('locked_by_id', sa.Integer(), nullable=True))
    op.add_column('scar', sa.Column('locked_pack_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scar', 'locked_pack_id')
    op.drop_column('scar', 'locked_by_id')
    op.drop_column('pack', 'did_scar')
    # ### end Alembic commands ###
