"""empty message

Revision ID: 16710174381b
Revises: 1db0a3bd6066
Create Date: 2020-10-14 14:20:53.008769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16710174381b'
down_revision = '1db0a3bd6066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cube_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('unlock', sa.Text(), nullable=True),
    sa.Column('multiunlock', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.Column('unlocked_by_id', sa.Integer(), nullable=True),
    sa.Column('unlocked_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['cube_id'], ['cube.id'], ),
    sa.ForeignKeyConstraint(['unlocked_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('achievement')
    # ### end Alembic commands ###
