"""locks for scars

Revision ID: 1a56589c2eca
Revises: c3f55e2c75a9
Create Date: 2020-10-04 15:20:24.506590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a56589c2eca'
down_revision = 'c3f55e2c75a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scar', sa.Column('lock_draft_id', sa.Integer(), nullable=True))
    op.add_column('scar', sa.Column('lock_participant_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scar', 'lock_participant_id')
    op.drop_column('scar', 'lock_draft_id')
    # ### end Alembic commands ###
