"""empty message

Revision ID: 22894a4c97d3
Revises: aea33c6d093c
Create Date: 2020-11-21 16:39:43.794307

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22894a4c97d3'
down_revision = 'aea33c6d093c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('state_json', mysql.MEDIUMTEXT(), nullable=True))
    op.drop_column('game', 'state_json_a')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('state_json_a', mysql.MEDIUMTEXT(), nullable=True))
    op.drop_column('game', 'state_json')
    # ### end Alembic commands ###
