"""empty message

Revision ID: 28b4c079b644
Revises: 7902daf7a003
Create Date: 2021-01-14 09:14:24.754979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28b4c079b644'
down_revision = '7902daf7a003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement', sa.Column('levelup', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('achievement', 'levelup')
    # ### end Alembic commands ###
