"""empty message

Revision ID: 2c5e21e08a37
Revises: 533a81cc360e
Create Date: 2020-10-03 08:43:42.086209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c5e21e08a37'
down_revision = '533a81cc360e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft', sa.Column('name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('draft', 'name')
    # ### end Alembic commands ###
