"""empty message

Revision ID: 2ce08dccb54e
Revises: a097f3f8a42e
Create Date: 2020-10-17 12:02:38.956696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ce08dccb54e'
down_revision = 'a097f3f8a42e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cube_card', sa.Column('latest_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cube_card', 'latest_id')
    # ### end Alembic commands ###
