"""empty message

Revision ID: 31310f263546
Revises: e8c0a746b768
Create Date: 2020-11-01 18:45:47.509782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31310f263546'
down_revision = 'e8c0a746b768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft', sa.Column('killed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('draft', 'killed')
    # ### end Alembic commands ###
