"""scryfall table

Revision ID: 37a0b78bc901
Revises: 417bfdcda598
Create Date: 2020-10-04 09:03:34.327367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37a0b78bc901'
down_revision = '417bfdcda598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scryfall_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=True),
    sa.Column('json', sa.String(length=16383), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scryfall_data_name'), 'scryfall_data', ['name'], unique=False)
    op.add_column('card', sa.Column('image_url', sa.String(length=511), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'image_url')
    op.drop_index(op.f('ix_scryfall_data_name'), table_name='scryfall_data')
    op.drop_table('scryfall_data')
    # ### end Alembic commands ###
