"""record pack number on scar

Revision ID: 3adc990846bb
Revises: 1a56589c2eca
Create Date: 2020-10-04 15:37:39.809561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3adc990846bb'
down_revision = '1a56589c2eca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scar', sa.Column('draft_pack_number', sa.Integer(), nullable=True, comment='The draft round in which this scar was applied, if any.'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scar', 'draft_pack_number')
    # ### end Alembic commands ###
