"""empty message

Revision ID: 3fa4aa040bf8
Revises: cbe4d53bbf84
Create Date: 2020-10-18 17:57:06.215510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fa4aa040bf8'
down_revision = 'cbe4d53bbf84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement', sa.Column('unlock_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('achievement', 'unlock_json')
    # ### end Alembic commands ###
