"""empty message

Revision ID: 411e68604099
Revises: 959ba493a298
Create Date: 2020-11-06 13:02:24.049387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411e68604099'
down_revision = '959ba493a298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('maindeck_ids', sa.Text(), nullable=True),
    sa.Column('sideboard_ids', sa.Text(), nullable=True),
    sa.Column('basic_lands', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['draft.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deck_timestamp'), 'deck', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deck_timestamp'), table_name='deck')
    op.drop_table('deck')
    # ### end Alembic commands ###
