"""empty message

Revision ID: 417bfdcda598
Revises: 2c5e21e08a37
Create Date: 2020-10-03 20:50:09.993329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417bfdcda598'
down_revision = '2c5e21e08a37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft', sa.Column('scar_rounds_str', sa.String(length=64), nullable=True))
    op.add_column('scar', sa.Column('added_timestamp', sa.DateTime(), nullable=True, comment='Time this scar was applied to a card.'))
    op.add_column('scar', sa.Column('notes_id', sa.String(length=256), nullable=True, comment='Thoughts the player had when adding this scar to the card.'))
    op.add_column('scar', sa.Column('reminder', sa.String(length=256), nullable=True, comment='Some additional explanation of what this scar does.'))
    op.add_column('scar', sa.Column('restrictions', sa.String(length=64), nullable=True, comment='Limitations on the kind of card this scar can be applied to.'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scar', 'restrictions')
    op.drop_column('scar', 'reminder')
    op.drop_column('scar', 'notes_id')
    op.drop_column('scar', 'added_timestamp')
    op.drop_column('draft', 'scar_rounds_str')
    # ### end Alembic commands ###
