"""XP on achievements

Revision ID: 4cdf04c16d18
Revises: c801713b18ba
Create Date: 2020-12-09 13:23:39.152808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cdf04c16d18'
down_revision = 'c801713b18ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement', sa.Column('xp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('achievement', 'xp')
    # ### end Alembic commands ###
