"""Remove deck.draft_id from deck

Revision ID: 4f134a71c27c
Revises: 8ba4b4c138b4
Create Date: 2021-02-05 18:36:32.026837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4f134a71c27c'
down_revision = '8ba4b4c138b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('deck_ibfk_1', 'deck', type_='foreignkey')
    op.drop_column('deck', 'draft_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deck', sa.Column('draft_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('deck_ibfk_1', 'deck', 'draft', ['draft_id'], ['id'])

    # Copy back the draft_id field
    op.execute('''
update deck
set draft_id = deck_draft_link.draft_id
where deck.id = deck_draft_link.deck_id
''')
    # ### end Alembic commands ###
