"""pack card table

Revision ID: 533a81cc360e
Revises: d607890317a7
Create Date: 2020-10-02 21:11:54.159418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '533a81cc360e'
down_revision = 'd607890317a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pack_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('draft_id', sa.Integer(), nullable=True),
    sa.Column('pack_id', sa.Integer(), nullable=True),
    sa.Column('picked_by_id', sa.Integer(), nullable=True),
    sa.Column('pick_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['draft_id'], ['draft.id'], ),
    sa.ForeignKeyConstraint(['pack_id'], ['pack.id'], ),
    sa.ForeignKeyConstraint(['picked_by_id'], ['participant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pack_card')
    # ### end Alembic commands ###
