"""empty message

Revision ID: 56d182479597
Revises: 8c43158c0d04
Create Date: 2020-10-05 17:17:54.448104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56d182479597'
down_revision = '8c43158c0d04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pack_card', sa.Column('picked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pack_card', 'picked_at')
    # ### end Alembic commands ###
