"""empty message

Revision ID: 56ff89ffbb0d
Revises: 016ff87010b4
Create Date: 2020-10-19 21:03:07.053288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56ff89ffbb0d'
down_revision = '016ff87010b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cube_card', sa.Column('removed_by_comment', sa.Text(), nullable=True))
    op.add_column('cube_card', sa.Column('removed_by_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cube_card', 'removed_by_timestamp')
    op.drop_column('cube_card', 'removed_by_comment')
    # ### end Alembic commands ###
