"""initial migration

Revision ID: 658187f6747f
Revises: 
Create Date: 2020-10-06 13:20:15.901474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658187f6747f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_base_card_name'), 'base_card', ['name'], unique=False)
    op.create_table('cube',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cube_active'), 'cube', ['active'], unique=False)
    op.create_table('draft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.Column('pack_size', sa.Integer(), nullable=True),
    sa.Column('num_packs', sa.Integer(), nullable=True),
    sa.Column('num_seats', sa.Integer(), nullable=True),
    sa.Column('scar_rounds_str', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_timestamp'), 'draft', ['timestamp'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('slack_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('cube_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('json', sa.Text(), nullable=True),
    sa.Column('cube_id', sa.Integer(), nullable=True),
    sa.Column('base_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['base_id'], ['base_card.id'], ),
    sa.ForeignKeyConstraint(['cube_id'], ['cube.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cube_card_active'), 'cube_card', ['active'], unique=False)
    op.create_table('pack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=True),
    sa.Column('seat_number', sa.Integer(), nullable=True),
    sa.Column('pack_number', sa.Integer(), nullable=True),
    sa.Column('num_picked', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['draft.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('draft_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['draft.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cube_card_version_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('json', sa.Text(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cube_card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cube_card_version_history_timestamp'), 'cube_card_version_history', ['timestamp'], unique=False)
    op.create_table('cube_edit_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Enum('add', 'remove', name='cubeedittype'), nullable=True),
    sa.Column('cube_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cube_card.id'], ),
    sa.ForeignKeyConstraint(['cube_id'], ['cube.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cube_edit_history_timestamp'), 'cube_edit_history', ['timestamp'], unique=False)
    op.create_table('pack_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('draft_id', sa.Integer(), nullable=True),
    sa.Column('pack_id', sa.Integer(), nullable=True),
    sa.Column('picked_by_id', sa.Integer(), nullable=True),
    sa.Column('pick_number', sa.Integer(), nullable=True),
    sa.Column('picked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cube_card.id'], ),
    sa.ForeignKeyConstraint(['draft_id'], ['draft.id'], ),
    sa.ForeignKeyConstraint(['pack_id'], ['pack.id'], ),
    sa.ForeignKeyConstraint(['picked_by_id'], ['seat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pack_card')
    op.drop_index(op.f('ix_cube_edit_history_timestamp'), table_name='cube_edit_history')
    op.drop_table('cube_edit_history')
    op.drop_index(op.f('ix_cube_card_version_history_timestamp'), table_name='cube_card_version_history')
    op.drop_table('cube_card_version_history')
    op.drop_table('seat')
    op.drop_table('pack')
    op.drop_index(op.f('ix_cube_card_active'), table_name='cube_card')
    op.drop_table('cube_card')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_draft_timestamp'), table_name='draft')
    op.drop_table('draft')
    op.drop_index(op.f('ix_cube_active'), table_name='cube')
    op.drop_table('cube')
    op.drop_index(op.f('ix_base_card_name'), table_name='base_card')
    op.drop_table('base_card')
    # ### end Alembic commands ###
