"""CubeSearch

Revision ID: 6a2a6d6e3205
Revises: 8ce98cb0063e
Create Date: 2021-03-14 18:07:43.938171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a2a6d6e3205'
down_revision = '8ce98cb0063e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cube_search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('cube_id', sa.Integer(), nullable=True),
    sa.Column('serialized', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['cube_id'], ['cube.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cube_search')
    # ### end Alembic commands ###
