"""draft and participant tables

Revision ID: 73bc2381742a
Revises: 9e542ddd45cc
Create Date: 2020-10-02 21:04:45.099518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73bc2381742a'
down_revision = '9e542ddd45cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.Column('pack_size', sa.Integer(), nullable=True),
    sa.Column('num_packs', sa.Integer(), nullable=True),
    sa.Column('num_seats', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('draft_id', sa.Integer(), nullable=True),
    sa.Column('seat', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['draft.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participant')
    op.drop_table('draft')
    # ### end Alembic commands ###
