"""remove level up from achievement

Revision ID: 797050175eda
Revises: 28b4c079b644
Create Date: 2021-01-15 13:52:27.194044

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '797050175eda'
down_revision = '28b4c079b644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('achievement', 'levelup')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement', sa.Column('levelup', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
