"""cards table no relationship

Revision ID: 7aa5a4b9ef70
Revises: fd9853d8ee72
Create Date: 2020-10-02 16:33:21.127253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aa5a4b9ef70'
down_revision = 'fd9853d8ee72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('added_by_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_name'), 'card', ['name'], unique=False)
    op.create_index(op.f('ix_card_timestamp'), 'card', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_timestamp'), table_name='card')
    op.drop_index(op.f('ix_card_name'), table_name='card')
    op.drop_table('card')
    # ### end Alembic commands ###
