"""Rename draft v2 link models to includ V2

Revision ID: 7b399823a94b
Revises: 96481d317da2
Create Date: 2021-06-12 14:39:01.199374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b399823a94b'
down_revision = '96481d317da2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_v2_user_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['draft_v2.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('draft_v2_achievement_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('ach_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ach_id'], ['achievement.id'], ),
    sa.ForeignKeyConstraint(['draft_id'], ['draft_v2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('draft_user_link')
    op.drop_table('draft_achievement_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_achievement_link',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('draft_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ach_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ach_id'], ['achievement.id'], name='draft_achievement_link_ibfk_1'),
    sa.ForeignKeyConstraint(['draft_id'], ['draft_v2.id'], name='draft_achievement_link_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('draft_user_link',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('draft_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['draft_v2.id'], name='draft_user_link_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='draft_user_link_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('draft_v2_achievement_link')
    op.drop_table('draft_v2_user_link')
    # ### end Alembic commands ###
