"""empty message

Revision ID: 7b68cf569197
Revises: 31310f263546
Create Date: 2020-11-03 11:37:22.969619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b68cf569197'
down_revision = '31310f263546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pack_card', sa.Column('faceup', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pack_card', 'faceup')
    # ### end Alembic commands ###
