"""update scarring for draft v2

Revision ID: 80c70022d701
Revises: bf0d599d33ab
Create Date: 2021-06-06 19:23:49.034697

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '80c70022d701'
down_revision = 'bf0d599d33ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faction')
    op.add_column('scar', sa.Column('locked_draft_id', sa.Integer(), nullable=True))
    op.drop_column('scar', 'locked_pack_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scar', sa.Column('locked_pack_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('scar', 'locked_draft_id')
    op.create_table('faction',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('cube_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('desc', mysql.TEXT(), nullable=True),
    sa.Column('memb', mysql.TEXT(), nullable=True),
    sa.Column('note', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['cube_id'], ['cube.id'], name='faction_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
