"""Indirect between draft and deck with DeckDraftLink

Revision ID: 8ba4b4c138b4
Revises: c6943fdf2ab7
Create Date: 2021-02-05 18:12:12.051871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ba4b4c138b4'
down_revision = 'c6943fdf2ab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deck_draft_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], ),
    sa.ForeignKeyConstraint(['draft_id'], ['draft.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('deck_list')

    op.execute('''insert into deck_draft_link (deck_id, draft_id) select id as deck_id, draft_id from deck;''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deck_list',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('draft_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('decklist', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['draft.id'], name='deck_list_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='deck_list_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('deck_draft_link')
    # ### end Alembic commands ###
