"""game completed timestamp

Revision ID: 96481d317da2
Revises: a0ca146b476d
Create Date: 2021-06-11 09:46:41.435642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96481d317da2'
down_revision = 'a0ca146b476d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('completed_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'completed_timestamp')
    # ### end Alembic commands ###
