"""Admin field on cubes

Revision ID: 98b48709a434
Revises: 7fa548aa4c62
Create Date: 2020-11-10 21:41:39.918991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b48709a434'
down_revision = '7fa548aa4c62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cube', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cube', 'admin')
    # ### end Alembic commands ###
