"""scars table

Revision ID: 9e542ddd45cc
Revises: fdcbb0bb3062
Create Date: 2020-10-02 16:47:33.000107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e542ddd45cc'
down_revision = 'fdcbb0bb3062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('added_by_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['added_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scar_timestamp'), 'scar', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scar_timestamp'), table_name='scar')
    op.drop_table('scar')
    # ### end Alembic commands ###
