"""Add cached pick info to cube cards

Revision ID: a7185807f0c0
Revises: 86c851b8935d
Create Date: 2021-02-12 09:34:15.386529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7185807f0c0'
down_revision = '86c851b8935d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cube_card', sa.Column('pick_info_avg', sa.Float(), nullable=True))
    op.add_column('cube_card', sa.Column('pick_info_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cube_card', 'pick_info_count')
    op.drop_column('cube_card', 'pick_info_avg')
    # ### end Alembic commands ###
