"""empty message

Revision ID: a965a8dce03a
Revises: 2ce08dccb54e
Create Date: 2020-10-18 08:20:11.443950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a965a8dce03a'
down_revision = '2ce08dccb54e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_notif_timestamp', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_pick_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_pick_timestamp')
    op.drop_column('user', 'last_notif_timestamp')
    # ### end Alembic commands ###
