"""empty message

Revision ID: b29598d633cc
Revises: 6a84d8e481b8
Create Date: 2020-10-26 17:40:33.341647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b29598d633cc'
down_revision = '6a84d8e481b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('ach_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ach_id'], ['achievement.id'], ),
    sa.ForeignKeyConstraint(['card_id'], ['cube_card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('achievement_link')
    # ### end Alembic commands ###
