"""empty message

Revision ID: b722bc009264
Revises: b69afb65d5df
Create Date: 2020-11-20 21:38:33.297766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b722bc009264'
down_revision = 'b69afb65d5df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('monikers_tsv', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'monikers_tsv')
    # ### end Alembic commands ###
