"""draft v2 models

Revision ID: bf0d599d33ab
Revises: 6a2a6d6e3205
Create Date: 2021-05-20 10:51:31.204922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf0d599d33ab'
down_revision = '6a2a6d6e3205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('data_json', mysql.MEDIUMTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_v2_timestamp'), 'draft_v2', ['timestamp'], unique=False)
    op.create_table('draft_user_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['draft_v2.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('draft_achievement_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('ach_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ach_id'], ['achievement.id'], ),
    sa.ForeignKeyConstraint(['draft_id'], ['draft_v2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('draft_achievement_link')
    op.drop_table('draft_user_link')
    op.drop_index(op.f('ix_draft_v2_timestamp'), table_name='draft_v2')
    op.drop_table('draft_v2')
    # ### end Alembic commands ###
