"""CubeCard.name

Revision ID: c6943fdf2ab7
Revises: 0d3ddd407bc1
Create Date: 2021-01-21 17:56:09.673560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6943fdf2ab7'
down_revision = '0d3ddd407bc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cube_card', sa.Column('name_tmp', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cube_card', 'name_tmp')
    # ### end Alembic commands ###
