"""Add xp stat to user model

Revision ID: c801713b18ba
Revises: cb7350767319
Create Date: 2020-12-09 09:04:37.411069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c801713b18ba'
down_revision = 'cb7350767319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('xp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'xp')
    # ### end Alembic commands ###
