"""empty message

Revision ID: ccc461eba3f2
Revises: 12cbef9e0868
Create Date: 2020-10-15 21:24:50.498226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccc461eba3f2'
down_revision = '12cbef9e0868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pack', sa.Column('scarred_this_round_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pack', 'scarred_this_round_id')
    # ### end Alembic commands ###
