"""empty message

Revision ID: de201b4a0423
Revises: e93d61f2cbe8
Create Date: 2020-11-18 08:40:40.861503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de201b4a0423'
down_revision = 'e93d61f2cbe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft', sa.Column('picks_per_pack', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('draft', 'picks_per_pack')
    # ### end Alembic commands ###
