"""empty message

Revision ID: e93d61f2cbe8
Revises: 702428af1717
Create Date: 2020-11-17 16:17:54.365948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e93d61f2cbe8'
down_revision = '702428af1717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cube', sa.Column('style_a', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cube', 'style_a')
    # ### end Alembic commands ###
