"""empty message

Revision ID: e9fd459ac4d6
Revises: a965a8dce03a
Create Date: 2020-10-18 11:30:45.781672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9fd459ac4d6'
down_revision = 'a965a8dce03a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('draft', 'complete')
    op.drop_column('pack', 'num_picked')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pack', sa.Column('num_picked', sa.INTEGER(), nullable=True))
    op.add_column('draft', sa.Column('complete', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
