"""empty message

Revision ID: f5e3351dc886
Revises: f9d86364f5db
Create Date: 2020-10-06 22:11:13.877504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5e3351dc886'
down_revision = 'f9d86364f5db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_card', sa.Column('last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('base_card', 'last_updated')
    # ### end Alembic commands ###
