"""empty message

Revision ID: fb248d1a0d01
Revises: ab66b37498e2
Create Date: 2020-12-22 12:23:47.196225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb248d1a0d01'
down_revision = 'ab66b37498e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('draft_ibfk_2', 'draft', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('draft_ibfk_2', 'draft', 'draft', ['parent_id'], ['id'])
    # ### end Alembic commands ###
